### ISSUE TITLE
Linux label is missing for nodes running archlinux

### ISSUE THREAD

**Issue by ncihnegn** [jenkinsci/platformlabeler-plugin#133]
We got only "arch", "rolling", "amd64", and their combinations.

**Comment by MarkEWaite** [comment]
Refer to the _[documentation](https://plugins.jenkins.io/platformlabeler)_ which lists the labels provided by the plugin.  The label 'linux' is intentionally not assigned by the plugin.

The [implied labels plugin](https://plugins.jenkins.io/implied-labels) can be used to automatically assign labels based on existing labels.  Refer to [my implied label definitions](https://github.com/MarkEWaite/docker-lfs/blob/lts-with-plugins/ref/org.jenkinsci.plugins.impliedlabels.Config.xml) for a way to map multiple Linux variants to the "linux" label.
