### ISSUE TITLE
Distinction between Win 10 and Win Server nodes

### ISSUE THREAD

**Issue by faandg** [jenkinsci/platformlabeler-plugin#612]
### What feature do you want to see added?

Hi,

Just added a Windows Server 2019 node but it is labelled as
`10.0 1809 amd64 amd64-windows amd64-windows-10.0 windows-10.0`
On the Manage Node page it is detected as Windows Server 2019 (amd64).
![image](https://user-images.githubusercontent.com/5772741/162450846-c3383c61-b353-4d18-98d8-0d11f31ebb9a.png)

I was checking the documentation of the Platform Labeller plugin and noticed there was no specific entry for WIndows Server, could you consider adding it?

**Comment by MarkEWaite** [comment]
> ### What feature do you want to see added?
> Hi,
> 
> Just added a Windows Server 2019 node but it is labelled as `10.0 1809 amd64 amd64-windows amd64-windows-10.0 windows-10.0` On the Manage Node page it is detected as Windows Server 2019 (amd64). ![image](https://user-images.githubusercontent.com/5772741/162450846-c3383c61-b353-4d18-98d8-0d11f31ebb9a.png)
> 
> I was checking the documentation of the Platform Labeler plugin and noticed there was no specific entry for Windows Server, could you consider adding it?

I don't have access to a Windows Server node that I could use for development and testing.  The [Microsoft documentation](https://docs.microsoft.com/en-us/windows/client-management/windows-version-search) seems to recommend `systeminfo` as the authoritative source of operating system details.

On my Windows 10 computer, it reports:

```
Host Name:                 MARKWAITE-B
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          MarkEWaite@live.com
Registered Organization:   N/A
Product ID:                00330-53082-77189-AAOEM
Original Install Date:     10/30/2021, 6:45:58 AM
System Boot Time:          4/4/2022, 7:42:42 PM
System Manufacturer:       Dell Inc.
System Model:              Precision 5540
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2592 Mhz
BIOS Version:              Dell Inc. 1.15.0, 12/9/2021
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-07:00) Mountain Time (US & Canada)
Total Physical Memory:     32,473 MB
Available Physical Memory: 12,468 MB
Virtual Memory: Max Size:  37,337 MB
Virtual Memory: Available: 7,559 MB
Virtual Memory: In Use:    29,778 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\MARKWAITE-B
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5010474
                           [02]: KB5004567
                           [03]: KB5008295
                           [04]: KB5011493
                           [05]: KB5009641
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6 AX200 160MHz
                                 Connection Name: Wi-Fi
                                 Status:          Media disconnected
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [03]: Realtek USB GbE Family Controller
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     172.16.16.249
                                 IP address(es)
                                 [01]: 172.16.16.185
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

What is displayed by Windows Server 2019 computers for that command?

**Comment by faandg** [comment]
systeminfo output for Windows Server (removed some company info)

![image](https://user-images.githubusercontent.com/5772741/162478988-7ba2167b-c506-493c-8659-d7f23bcdb27f.png)

Looking more into Windows version info it seems they share this 'base' version

![image](https://user-images.githubusercontent.com/5772741/162479498-34832287-2bbe-4161-ac37-0a06b4bbf1ff.png)

**Comment by MarkEWaite** [comment]
I've implemented the feature by adding a new label that uses the value of the JVM `os.name` property.  When it detects "Windows Server" it adds the `WindowServer2016
